/**
 * All user-facing text lives here in Spanish (the mockup's language). Centralized
 * so copy stays consistent and the product could be localized later. Product
 * name is always "SowyVid".
 */
export const copy = {
  brand: 'SowyVid',
  header: {
    help: 'Ayuda',
    settings: 'Ajustes',
  },
  nav: {
    home: 'Inicio',
    assistant: 'Asistente',
    myCommercials: 'Mis comerciales',
    music: 'Música',
    material: 'Material',
  },
  promo: {
    title: 'Comerciales que venden por ti',
    body: 'Rápido, fácil y hecho para negocios como el tuyo.',
    shopSign: 'TU NEGOCIO',
  },
  step1: {
    n: 1,
    title: 'Cuéntanos qué quieres promocionar',
    subtitle: 'Escribe en pocas palabras qué quieres comunicar.',
    placeholder: 'Ejemplo: Reparación de pantallas de iPhone el mismo día',
    continue: 'Continuar',
  },
  step2: {
    n: 2,
    title: 'Agrega tu material',
    subtitle: 'Sube fotos y videos. Entre más real, mejores resultados.',
    dropzone: 'Arrastra aquí o selecciona',
    sources: {
      thisDevice: 'Este equipo',
      myPhone: 'Mi teléfono',
      saved: 'Material guardado',
    },
    tipLabel: 'Consejo:',
    tip: 'Incluye fotos de tu negocio, productos, equipo y resultados.',
  },
  step3: {
    n: 3,
    title: 'Elige tu estilo',
    subtitle: 'Creamos 3 versiones diferentes para ti.',
    seeAll: 'Ver las 3 versiones',
    styles: [
      {
        id: 'direct',
        name: 'Directo y rápido',
        description: 'Enfocado en velocidad y resultados.',
      },
      {
        id: 'trust',
        name: 'Confianza y calidad',
        description: 'Transmite profesionalismo y confianza.',
      },
      {
        id: 'before-after',
        name: 'Antes y después',
        description: 'Muestra la transformación que obtienes.',
      },
    ],
  },
  step4: {
    n: 4,
    title: 'Tu comercial está listo',
    subtitle: 'Descarga, comparte y haz crecer tu negocio.',
    download: 'Descargar video',
    createAnother: 'Crear otra versión',
    notReadyTitle: 'Aún no está listo',
    notReadyBody: 'Completa los pasos anteriores y crearemos tu comercial.',
  },
  trust: [
    {
      icon: 'image' as const,
      title: 'Hecho con tu material',
      body: 'Usamos tus fotos y videos reales.',
    },
    {
      icon: 'phone' as const,
      title: 'Listo para redes sociales',
      body: 'Formato vertical optimizado.',
    },
    {
      icon: 'check-circle' as const,
      title: 'Sin experiencia necesaria',
      body: 'Nosotros hacemos el trabajo por ti.',
    },
  ],
  audio: {
    title: 'Sonido de tu comercial',
    musicLabel: 'Música del comercial',
    noMusic: 'Sin música',
    musicVolume: 'Volumen de música',
    noMusicImported: 'No agregaste música de fondo.',
    sourceAudioTitle: 'Audio original del video',
    sourceAudioEnable: 'Usar audio original',
    sourceAudioVolume: 'Volumen del audio original',
    sourceAudioHint: 'Apagado por defecto — actívalo si quieres oír el sonido de tu video.',
    videoNoSound: 'Este video no contiene sonido.',
    silentWarning: 'Este comercial no tiene audio.',
  },
  home: {
    currentLabel: 'Comercial actual:',
    newCommercial: 'Nuevo comercial',
    unnamed: 'Sin nombre',
  },
  library: {
    title: 'Mis comerciales',
    empty: 'Aún no tienes comerciales. Crea el primero desde Inicio.',
    open: 'Abrir',
    rename: 'Renombrar',
    duplicate: 'Duplicar',
    remove: 'Eliminar',
    openLastVideo: 'Abrir último video',
    openFolder: 'Abrir carpeta',
    videosTitle: 'Videos creados',
    noVideos: 'Este comercial aún no tiene videos exportados.',
    fileMissing: 'Archivo no encontrado',
    play: 'Reproducir',
    anotherVersion: 'Crear otra versión',
    status: { draft: 'Borrador', ready: 'Listo', exported: 'Exportado' },
    deleteTitle: 'Eliminar comercial',
    deleteBody:
      'Se eliminará el proyecto y su material administrado. Esta acción no se puede deshacer.',
    deleteKeepExports: 'Conservar los videos ya exportados en mi computadora',
    deleteConfirm: 'Eliminar el proyecto y su material administrado',
    cancel: 'Cancelar',
  },
  mediaRemove: {
    title: 'Este archivo se está usando en tu comercial.',
    replace: 'Reemplazar archivo',
    removeAndDelete: 'Quitar del comercial y eliminar',
    cancel: 'Cancelar',
  },
  music: {
    title: 'Música',
    tabLibrary: 'Biblioteca',
    tabSuno: 'Crear con Suno',
    add: 'Agregar música',
    empty: 'Tu biblioteca de música está vacía. Agrega una canción para empezar.',
    searchPlaceholder: 'Buscar por título o archivo…',
    allSources: 'Todas las fuentes',
    allMoods: 'Todos los ambientes',
    play: 'Reproducir',
    pause: 'Pausar',
    previewVolume: 'Volumen de escucha',
    useInCommercial: 'Usar en este comercial',
    selected: 'En uso en este comercial',
    editData: 'Editar datos',
    replaceInCommercial: 'Reemplazar en este comercial',
    reveal: 'Mostrar archivo',
    remove: 'Quitar de la biblioteca',
    usedByCount: (n: number) => (n === 1 ? 'Usada en 1 comercial' : `Usada en ${n} comerciales`),
    notUsed: 'Sin usar todavía',
    missingFile: 'Archivo no encontrado',
    invalidFile: 'Archivo no válido',
    save: 'Guardar',
    cancel: 'Cancelar',
    fields: {
      title: 'Título',
      creator: 'Autor / artista',
      source: 'Origen',
      sourceUrl: 'Enlace o referencia',
      mood: 'Ambiente (separado por comas)',
      energy: 'Energía',
      vocal: 'Voz',
      license: 'Uso permitido',
      licenseNotes: 'Notas de licencia',
      commercialUse: 'Confirmo que puedo usarla en un comercial',
    },
    source: {
      imported: 'Importada por el dueño',
      'suno-manual': 'Creada en Suno (manual)',
      licensed: 'Música con licencia',
      original: 'Producción propia',
      unknown: 'Origen desconocido',
    },
    license: {
      'commercial-confirmed': 'Confirmada para uso comercial',
      'personal-only': 'Solo uso personal',
      'needs-review': 'Falta revisar la licencia',
      unknown: 'Sin confirmar',
    },
    energy: { calm: 'Tranquila', balanced: 'Equilibrada', energetic: 'Enérgica', unknown: 'Sin definir' },
    vocal: { instrumental: 'Instrumental', vocal: 'Con voz', unknown: 'Sin definir' },
    licenseWarning: 'SowyVid no confirma que tengas derechos sobre esta música. Revisa su uso.',
    // Safe deletion dialog
    inUseTitle: 'Esta música se está usando en:',
    replaceInAll: 'Reemplazar en todos los comerciales',
    removeFromAll: 'Quitar de todos y eliminar',
    chooseReplacement: 'Elige la música de reemplazo',
    // Suno
    suno: {
      intro:
        'SowyVid escribe el brief. Tú creas la música en tu cuenta de Suno, la descargas y la importas aquí.',
      generate: 'Generar brief',
      needCommercial: 'Primero crea tu comercial para generar el brief de música.',
      copy: 'Copiar brief',
      copied: 'Brief copiado',
      openSuno: 'Abrir Suno',
      markCreated: 'Ya la creé en Suno',
      importResult: 'Importar la canción descargada',
      wantsVocals: 'Quiero música con voz',
      instrumentalNote: 'Por defecto es instrumental (mejor para un comercial).',
      purpose: 'Propósito',
      genre: 'Género / estilo',
      mood: 'Ambiente',
      energyLabel: 'Energía',
      tempo: 'Tempo',
      instruments: 'Instrumentos',
      vocals: 'Voz',
      duration: 'Duración',
      intro2: 'Entrada',
      ending: 'Final',
      loopFade: 'Repetición / fade',
      avoid: 'Evitar',
      savedToLibrary: 'Guardada en tu biblioteca y lista para usar.',
    },
  },
  textEditor: {
    edit: 'Editar texto',
    done: 'Terminar edición',
    title: 'Mueve el texto',
    scene: 'Escena',
    selected: 'Texto seleccionado:',
    hint: 'Toca un texto para seleccionarlo y arrástralo a donde quieras.',
    size: 'Tamaño',
    width: 'Ancho',
    alignment: 'Alineación',
    lock: 'Fijar posición',
    unlock: 'Desbloquear',
    resetElement: 'Restablecer posición',
    resetScene: 'Restablecer texto de esta escena',
    unsafe: 'El texto está muy cerca del borde. Puede cortarse en algunas redes.',
    copyTo: 'Copiar posición a…',
    copyAll: 'Todas las escenas',
    copySame: 'Escenas con el mismo tipo de texto',
    copyNext: 'Siguiente escena',
    cancel: 'Cancelar',
    presets: {
      top: 'Arriba',
      center: 'Centro',
      bottom: 'Abajo',
      topCorner: 'Esquina superior',
      bottomCorner: 'Esquina inferior',
    },
  },
  assistant: {
    title: 'Asistente de comerciales',
    subtitle: 'Cuéntame qué quieres promocionar y te armo un plan.',
    placeholder: 'Ejemplo: Quiero promocionar un Samsung A16 nuevo de 128 GB por $179.',
    analyze: 'Analizar',
    reanalyze: 'Volver a analizar',
    detectedProduct: 'Producto detectado',
    toConfirm: 'Información por confirmar',
    toConfirmHint: 'Opcional. Entre más datos reales, más fuerte tu comercial.',
    knownFacts: 'Datos confirmados',
    angle: 'Enfoque recomendado',
    narration: 'Narración',
    overlays: 'Texto en pantalla',
    visualPlan: 'Plan visual',
    externalClips: 'Clips externos sugeridos',
    externalNone: 'Ninguno — este comercial puede hacerse con tus fotos.',
    externalNote: 'Un clip corto puede ayudar en esta escena. Lo revisarás antes de generar nada.',
    warnings: 'Avisos',
    createCommercial: 'Crear comercial',
    // AI
    aiPropose: 'Crear propuesta con AI',
    aiReview: 'Revisar propuesta',
    aiApply: 'Aplicar propuesta',
    aiRegenerate: 'Regenerar',
    aiWithout: 'Usar versión sin AI',
    aiPrivacyTitle: 'Esto es lo único que se enviaría a la AI',
    aiPrivacyNote: 'Solo texto. Nunca se envían tus fotos, videos, música ni datos privados.',
    aiContinue: 'Continuar con AI',
    aiNotConfigured: 'Aún no has configurado una AI. Puedes seguir con la versión automática.',
    cancel: 'Cancelar',
    // scene media plan labels
    mediaPlan: {
      'owner-photo': 'Tu foto',
      'owner-video': 'Tu video',
      'generated-video': 'Video externo',
      'text-only': 'Solo texto',
    },
    roleLabel: {
      hook: 'Gancho',
      need: 'Contexto',
      solution: 'Producto',
      benefit: 'Beneficio',
      offer: 'Oferta',
      trust: 'Confianza',
      cta: 'Llamado a la acción',
    },
    created: 'Comercial creado desde el plan.',
  },
  common: {
    unavailable: 'Disponible pronto',
    unavailableHint: 'Esta función estará disponible en una próxima versión.',
  },
} as const

export type StyleOption = (typeof copy.step3.styles)[number]
